---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Naming/BlockForwarding:
  EnforcedStyle: explicit

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 150

###########
# METRICS #
###########

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

#########
# RSPEC #
#########

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 9

RSpec/MessageSpies:
  EnforcedStyle: receive
