inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Style/InvertibleUnlessCondition:
  Exclude:
    - "lib/sidekiq_alive.rb"
